version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -extldflags "-fno-PIC -static"
      - -trimpath
      - -X=github.com/prometheus/common/version.Version={{.Version}}
      - -X=github.com/prometheus/common/version.Branch={{.Branch}}

checksum:
  name_template: "checksums.txt"
